"""add translation mode to user

Revision ID: 2f39cf587a31
Revises: f87282a78937
Create Date: 2025-10-27 21:15:50.441446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f39cf587a31'
down_revision: Union[str, None] = 'f87282a78937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем колонку с nullable=True
    op.add_column('users', sa.Column('translation_mode', sa.String(length=10), nullable=True))
    
    # Устанавливаем значение по умолчанию для существующих записей
    op.execute("UPDATE users SET translation_mode = 'DE-RU' WHERE translation_mode IS NULL")
    
    # Теперь делаем поле NOT NULL
    op.alter_column('users', 'translation_mode', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'translation_mode')
    # ### end Alembic commands ###
