"""Initial migration

Revision ID: f87282a78937
Revises: 
Create Date: 2025-10-23 19:28:33.030322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87282a78937'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('title_de', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('master_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lemma', sa.String(length=255), nullable=False),
    sa.Column('article', sa.Enum('DER', 'DIE', 'DAS', 'NONE', name='article'), nullable=True),
    sa.Column('pos', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'OTHER', name='partofspeech'), nullable=False),
    sa.Column('cefr', sa.Enum('A0', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('translation_ru', sa.String(length=500), nullable=False),
    sa.Column('example_de', sa.Text(), nullable=True),
    sa.Column('example_ru', sa.Text(), nullable=True),
    sa.Column('plural', sa.String(length=255), nullable=True),
    sa.Column('separable_prefix', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('selected_level', sa.Enum('A0', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Enum('A0', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['master_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['master_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_items')
    op.drop_table('word_categories')
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('master_words')
    op.drop_table('categories')
    # ### end Alembic commands ###
